title: "Ali El Masri's Portfolio"
description: "# Hello Adventurers and Data Lovers! 🎢📊"
theme: jekyll-theme-cayman
baseurl: "/Portfolio" 
url: "https://elmasri-ali.github.io" 
github_username: elmasri-ali

# Optional settings
show_downloads: 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-fontawesome
